import type { MetadataRoute } from "next";
import { site } from "@/config/site";

/** Web app manifest — install metadata for mobile/PWA contexts. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${site.name} — Portfolio`,
    short_name: site.shortName,
    description: site.tagline,
    start_url: "/",
    display: "standalone",
    background_color: "#080f1f",
    theme_color: "#080f1f",
    icons: [
      // Scalable SVG for browsers that support it.
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml" },
      // Raster PNGs (generated by scripts/generate-assets.mjs).
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable variant with a safe zone for Android adaptive icons.
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
