import { posts } from "./posts";
import {
  BLOG_AUTHOR,
  BlogCategory,
  headingId,
  type ArticleSource,
  type BlogArticle,
  type TocEntry,
} from "./types";

export { BlogCategory, Difficulty, type BlogArticle, type TocEntry } from "./types";

/**
 * src/content/blog/index.ts
 * ------------------------------------------------------------
 * Enriches the authored posts with every derivable field —
 * reading time, table of contents, cover art, canonical slug,
 * author block, OG/Twitter fields — so nothing is duplicated
 * and nothing can go stale.
 *
 * To publish a post: append an ArticleSource to posts.ts.
 * Pages, sitemap, search, related links, and the AI assistant
 * pick it up automatically on the next build.
 */

/** Cover art per category (generated by scripts/generate-assets.mjs). */
const categoryCoverSlug: Record<BlogCategory, string> = {
  [BlogCategory.React]: "react",
  [BlogCategory.NextJS]: "nextjs",
  [BlogCategory.TypeScript]: "typescript",
  [BlogCategory.JavaScript]: "javascript",
  [BlogCategory.CSS]: "css",
  [BlogCategory.Backend]: "backend",
  [BlogCategory.FastAPI]: "fastapi",
  [BlogCategory.Databases]: "databases",
  [BlogCategory.DevOps]: "devops",
  [BlogCategory.Linux]: "linux",
  [BlogCategory.AI]: "ai",
  [BlogCategory.Performance]: "performance",
  [BlogCategory.Career]: "career",
  [BlogCategory.Journey]: "journey",
  [BlogCategory.Projects]: "projects",
};

function wordCount(source: ArticleSource): number {
  const text = `${source.articleBody} ${source.conclusion ?? ""}`;
  return text.split(/\s+/).filter(Boolean).length;
}

function toc(source: ArticleSource): TocEntry[] {
  return [...source.articleBody.matchAll(/^## (.+)$/gm)].map((m) => ({
    id: headingId(m[1]),
    text: m[1],
  }));
}

function enrich(source: ArticleSource): BlogArticle {
  const words = wordCount(source);
  return {
    ...source,
    ...BLOG_AUTHOR,
    canonicalSlug: source.slug,
    wordCount: words,
    readingTime: Math.max(1, Math.round(words / 220)),
    tableOfContents: toc(source),
    featuredImage: `/blog-covers/${categoryCoverSlug[source.category]}.svg`,
    coverImageAlt: `Cover art for "${source.title}" — ${source.category}`,
    ogTitle: source.seoTitle,
    ogDescription: source.seoDescription,
    twitterTitle: source.title,
    twitterDescription: source.description,
  };
}

/** All articles, newest first — the canonical order. */
export const blogArticles: BlogArticle[] = posts
  .map(enrich)
  .sort((a, b) => b.publishDate.localeCompare(a.publishDate));

export const featuredArticles = blogArticles.filter((a) => a.featured);
export const recentArticles = blogArticles.slice(0, 5);

/** "Trending" = featured first, then most-referenced by other posts. */
export const trendingArticles = [...blogArticles]
  .sort((a, b) => {
    const refs = (slug: string) =>
      blogArticles.filter((p) => p.relatedPosts.includes(slug)).length;
    return (
      Number(b.featured) - Number(a.featured) || refs(b.slug) - refs(a.slug)
    );
  })
  .slice(0, 5);

export const blogCategories = [
  ...new Set(blogArticles.map((a) => a.category)),
];

export function articleBySlug(slug: string): BlogArticle | undefined {
  return blogArticles.find((a) => a.slug === slug);
}

/** Prev/next in the canonical (newest-first) order. */
export function adjacentArticles(slug: string): {
  newer: BlogArticle | null;
  older: BlogArticle | null;
} {
  const idx = blogArticles.findIndex((a) => a.slug === slug);
  if (idx === -1) return { newer: null, older: null };
  return {
    newer: idx > 0 ? blogArticles[idx - 1] : null,
    older: idx < blogArticles.length - 1 ? blogArticles[idx + 1] : null,
  };
}

/** Related posts, resolved and padded with same-category picks. */
export function relatedArticles(article: BlogArticle, count = 3): BlogArticle[] {
  const explicit = article.relatedPosts
    .map((slug) => articleBySlug(slug))
    .filter((a): a is BlogArticle => Boolean(a));
  const padding = blogArticles.filter(
    (a) =>
      a.slug !== article.slug &&
      a.category === article.category &&
      !explicit.includes(a)
  );
  return [...explicit, ...padding].slice(0, count);
}

/** Reading collections — curated entry points. */
export const readingCollections: { id: string; title: string; description: string; slugs: string[] }[] = [
  {
    id: "start-here",
    title: "Start Here",
    description: "The journey, the method, and the mindset.",
    slugs: [
      "my-journey-into-full-stack-development",
      "my-approach-to-learning-new-technologies",
      "continuous-learning-in-software-development",
    ],
  },
  {
    id: "backend",
    title: "Backend & APIs",
    description: "REST APIs, debugging, and coding habits in practice.",
    slugs: [
      "understanding-rest-apis-through-projects",
      "debugging-taught-me-more-than-success",
      "building-better-coding-habits",
    ],
  },
  {
    id: "devops",
    title: "DevOps & Cloud",
    description: "Docker, Git, and cloud concepts learned step by step.",
    slugs: [
      "why-i-started-learning-docker",
      "my-experience-with-git-and-github",
      "learning-cloud-concepts-step-by-step",
    ],
  },
];

/** Reading series — ordered, connected sequences. */
export const readingSeries: { id: string; title: string; description: string; slugs: string[] }[] = [
  {
    id: "learning-by-building",
    title: "Learning by Building",
    description: "The practical learning method, from first project to lasting habits.",
    slugs: [
      "my-journey-into-full-stack-development",
      "why-small-projects-matter",
      "my-approach-to-learning-new-technologies",
      "continuous-learning-in-software-development",
    ],
  },
  {
    id: "ship-it",
    title: "Ship It",
    description: "From version control to containers to the cloud.",
    slugs: [
      "my-experience-with-git-and-github",
      "why-i-started-learning-docker",
      "learning-cloud-concepts-step-by-step",
    ],
  },
];

/** Lightweight card data — safe to pass into client components. */
export interface ArticleCard {
  slug: string;
  title: string;
  description: string;
  category: BlogCategory;
  tags: string[];
  publishDate: string;
  readingTime: number;
  featured: boolean;
  keywords: string[];
}

export const articleCards: ArticleCard[] = blogArticles.map((a) => ({
  slug: a.slug,
  title: a.title,
  description: a.description,
  category: a.category,
  tags: a.tags,
  publishDate: a.publishDate,
  readingTime: a.readingTime,
  featured: a.featured,
  keywords: a.keywords,
}));
